#! /usr/bin/env ruby

puts "Donnez moi un premier nombre"
nombre1 = gets.to_i

puts "Donnez moi un deuxieme nombre"
nombre2 = gets.to_i

puts "C'est parti !"
puts "#{nombre1} + #{nombre2} = #{nombre1 + nombre2}"
puts "#{nombre1} - #{nombre2} = #{nombre1 - nombre2}"
puts "#{nombre1} / #{nombre2} = #{nombre1 / nombre2}"
puts "#{nombre1} x #{nombre2} = #{nombre1 * nombre2}"
