#! /usr/bin/env ruby

def array_des_noms(nom)
  array = [nom.each{ |k, v| nom[k]=*v}]

  puts array.class
  puts array
  array.map! {|elt| elt.gsub(/}/, '')}
  puts array
  #  delete('"', '[/', '/]', '=>', '{/', '/}')}
  puts array
  #m = array.map! {|string| string.titleize}
    #m = string.gsub(/\(["[]=>{})/, '')
    #puts m
end
personnes = {
  "jean" => "valjean",
  "grace" => "hopper",
  "xavier" => "niel",
  "fifi" => "brindacier"
  }

p array_des_noms(personnes)
