#! /usr/bin/env ruby

puts "Hey, what's up ?"
answer = gets.to_s
answer = answer.chomp

while true
  print "I got that ! Anything else ?"
  answer = gets.chomp
  if answer == "STOP" then
    break
  end
end
